ALTER TABLE PROFITS.CUSTOMER
    ALTER COLUMN DATE_OF_BIRTH
        SET DATA TYPE DATE;

-- 2. CUST_TYPE: VARCHAR(255) → CHAR(1)
ALTER TABLE PROFITS.CUSTOMER
    ALTER COLUMN CUST_TYPE
        SET DATA TYPE CHAR(1);

-- 3. CUST_STATUS: VARCHAR(1) → CHAR(1)
ALTER TABLE PROFITS.CUSTOMER
    ALTER COLUMN CUST_STATUS
        SET DATA TYPE CHAR(1);

-- 4. FIRST_NAME: VARCHAR(255) → CHAR(20)
ALTER TABLE PROFITS.CUSTOMER
    ALTER COLUMN FIRST_NAME
        SET DATA TYPE CHAR(20);

-- 5. MIDDLE_NAME: VARCHAR(255) → VARCHAR(15)
ALTER TABLE PROFITS.CUSTOMER
    ALTER COLUMN MIDDLE_NAME
        SET DATA TYPE VARCHAR(15);


ALTER TABLE PROFITS.CUSTOMER
    DROP COLUMN LAST_NAME;

-- 1. Reorganize the table
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUSTOMER');


-- 1. FK_USRCODE: VARCHAR(8) → CHAR(8)
ALTER TABLE PROFITS.GLI_TRX_EXTRACT
    ALTER COLUMN FK_USRCODE
        SET DATA TYPE CHAR(8);

CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.GLI_TRX_EXTRACT');



-- 2. TRN_SNUM: BIGINT → INTEGER
-- WARNING: Will fail if any value > 2,147,483,647
ALTER TABLE PROFITS.GLI_TRX_EXTRACT
    ALTER COLUMN TRN_SNUM
        SET DATA TYPE INTEGER;


CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.GLI_TRX_EXTRACT');

CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE PROFITS.GLI_TRX_EXTRACT AND INDEXES ALL');


--Other Id
-- 1. FKGH_HAS_BEEN_ISSU → CHAR(5)
ALTER TABLE PROFITS.OTHER_ID
    ALTER COLUMN FKGH_HAS_BEEN_ISSU
        SET DATA TYPE CHAR(5);

CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.OTHER_ID');


-- 2. FKGH_HAS_TYPE → CHAR(5)
ALTER TABLE PROFITS.OTHER_ID
    ALTER COLUMN FKGH_HAS_TYPE
        SET DATA TYPE CHAR(5);

CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.OTHER_ID');


-- 3. ID_NO → CHAR(20)
ALTER TABLE PROFITS.OTHER_ID
    ALTER COLUMN ID_NO
        SET DATA TYPE CHAR(20);

CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.OTHER_ID');


ALTER TABLE PROFITS.OTHER_ID DROP COLUMN DESCRIPTION;
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.OTHER_ID');

ALTER TABLE PROFITS.OTHER_ID DROP COLUMN PARAMETER_TYPE;
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.OTHER_ID');

ALTER TABLE PROFITS.OTHER_ID DROP COLUMN SHORT_DESCRIPTION;
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.OTHER_ID');


--generic detail

-- 1. FK_GENERIC_HEADPAR → CHAR(5)
ALTER TABLE PROFITS.GENERIC_DETAIL
    ALTER COLUMN FK_GENERIC_HEADPAR
        SET DATA TYPE CHAR(5);

CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.GENERIC_DETAIL');


-- 2. PARAMETER_TYPE → CHAR(5)
ALTER TABLE PROFITS.GENERIC_DETAIL
    ALTER COLUMN PARAMETER_TYPE
        SET DATA TYPE CHAR(5);

CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.GENERIC_DETAIL');


-- 3. SHORT_DESCRIPTION → CHAR(10)
ALTER TABLE PROFITS.GENERIC_DETAIL
    ALTER COLUMN SHORT_DESCRIPTION
        SET DATA TYPE CHAR(10);

CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.GENERIC_DETAIL');


ALTER TABLE PROFITS.GENERIC_DETAIL DROP COLUMN KPI_INFO_NUMBER;
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.GENERIC_DETAIL');

ALTER TABLE PROFITS.GENERIC_DETAIL DROP COLUMN KPI_INFO_TEXT;
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.GENERIC_DETAIL');

ALTER TABLE PROFITS.GENERIC_DETAIL DROP COLUMN MIDDLE_NAME;
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.GENERIC_DETAIL');

--customer category

-- 1. FK_CATEGORYCATEGOR → CHAR(8)
ALTER TABLE PROFITS.CUSTOMER_CATEGORY
    ALTER COLUMN FK_CATEGORYCATEGOR
        SET DATA TYPE CHAR(8);

CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUSTOMER_CATEGORY');


-- 2. FK_GENERIC_DETAFK → CHAR(5)
ALTER TABLE PROFITS.CUSTOMER_CATEGORY
    ALTER COLUMN FK_GENERIC_DETAFK
        SET DATA TYPE CHAR(5);

CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUSTOMER_CATEGORY');

CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE PROFITS.CUSTOMER_CATEGORY AND INDEXES ALL');



--customer address

ALTER TABLE PROFITS.CUST_ADDRESS ALTER COLUMN COMMUNICATION_ADDR SET DATA TYPE CHAR(1);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUST_ADDRESS');

ALTER TABLE PROFITS.CUST_ADDRESS ALTER COLUMN ADDRESS_TYPE SET DATA TYPE CHAR(1);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUST_ADDRESS');

ALTER TABLE PROFITS.CUST_ADDRESS ALTER COLUMN CITY SET DATA TYPE CHAR(30);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUST_ADDRESS');

ALTER TABLE PROFITS.CUST_ADDRESS ALTER COLUMN REGION SET DATA TYPE VARCHAR(20);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUST_ADDRESS');

ALTER TABLE PROFITS.CUST_ADDRESS ALTER COLUMN ADDRESS_1 SET DATA TYPE VARCHAR(40);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUST_ADDRESS');

ALTER TABLE PROFITS.CUST_ADDRESS ALTER COLUMN ADDRESS_2 SET DATA TYPE VARCHAR(40);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUST_ADDRESS');

ALTER TABLE PROFITS.CUST_ADDRESS ALTER COLUMN ENTRY_COMMENTS SET DATA TYPE VARCHAR(250);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUST_ADDRESS');

ALTER TABLE PROFITS.CUST_ADDRESS ALTER COLUMN INTERNET_ADDRESS SET DATA TYPE VARCHAR(100);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUST_ADDRESS');

ALTER TABLE PROFITS.CUST_ADDRESS ALTER COLUMN E_MAIL SET DATA TYPE VARCHAR(60);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUST_ADDRESS');

ALTER TABLE PROFITS.CUST_ADDRESS ALTER COLUMN TELEPHONE_2 SET DATA TYPE VARCHAR(15);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUST_ADDRESS');

ALTER TABLE PROFITS.CUST_ADDRESS ALTER COLUMN TELEPHONE_3 SET DATA TYPE VARCHAR(15);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUST_ADDRESS');

ALTER TABLE PROFITS.CUST_ADDRESS ALTER COLUMN ADDRESS_3 SET DATA TYPE VARCHAR(40);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUST_ADDRESS');

ALTER TABLE PROFITS.CUST_ADDRESS ALTER COLUMN ADDRESS_4 SET DATA TYPE VARCHAR(40);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUST_ADDRESS');

ALTER TABLE PROFITS.CUST_ADDRESS ALTER COLUMN ADDRESS_5 SET DATA TYPE VARCHAR(40);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUST_ADDRESS');

ALTER TABLE PROFITS.CUST_ADDRESS ALTER COLUMN ADDRESS_6 SET DATA TYPE VARCHAR(40);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PROFITS.CUST_ADDRESS');